// TODO Use https://baconipsum.com/api/?type=meat-and-filler&paras=7
Future<List<String>> fetchLorem() => Future.value([
      "Occaecat ad qui ribeye beef ribs, ullamco consectetur boudin et.  Consequat capicola shankle tri-tip strip steak ut mollit.  Aute ribeye beef, pariatur nisi proident aliqua pork belly swine in biltong boudin.  Flank cupidatat tenderloin biltong proident.",
      "Veniam bacon chicken nisi filet mignon.  Drumstick duis culpa shank.  Pork proident leberkas, chislic cow jerky hamburger chuck.  Sausage tri-tip buffalo turducken, ribeye dolor dolore shank spare ribs flank esse elit quis sirloin.  Ad nostrud buffalo nisi swine dolore sirloin chicken.",
      "Voluptate ball tip anim sausage eu meatball jowl consequat laborum cupim sed laboris.  Commodo in minim shank, culpa strip steak anim voluptate beef laborum chuck aliquip nulla reprehenderit.  Short ribs exercitation chicken, irure boudin prosciutto do beef ribs duis veniam shoulder dolore.  Frankfurter prosciutto short loin ham hock.",
      "Drumstick bresaola filet mignon ullamco alcatra eu buffalo aliquip capicola, dolore meatloaf.  Kielbasa jowl landjaeger meatball.  Swine pork loin sed aute voluptate, picanha dolore velit frankfurter reprehenderit minim turducken ground round strip steak aliqua.  Aliqua commodo consequat, beef irure ut tongue in exercitation fatback lorem boudin laborum.  Chuck cupidatat landjaeger ex pork belly.",
      "Burgdoggen jowl reprehenderit ad, alcatra frankfurter commodo.  Mollit jowl ea, elit sirloin dolore in cow ut ham andouille in magna sunt shankle.  Officia et meatloaf eu occaecat exercitation, swine ground round deserunt turducken shank.  Filet mignon burgdoggen kielbasa biltong.  Do venison tail, chuck ham hock culpa bresaola chicken short ribs consequat ut.",
      "Ea consectetur chislic swine pariatur pancetta tempor ad aliqua sirloin turkey non.  Nulla frankfurter chicken jowl sunt dolore occaecat brisket in.  Chicken officia lorem, veniam nisi deserunt ipsum jerky venison tempor pariatur cupim ullamco dolore laborum.  Shank pariatur occaecat aliquip.",
      "Veniam bacon reprehenderit chislic.  Qui cupidatat short loin ham pork chuck do magna.  Sirloin in consectetur do est.  Aliquip laboris brisket pork belly andouille shankle."
    ]);
